apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksdeploydemo 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdeploydemo
  template:
    metadata:
      labels:
        app: aksdeploydemo 
    spec:
      containers:
        - name: aksdeploydemo 
          image: demoprojectps.azurecr.io/aksdeploydemo
          ports:
          - containerPort: 80